backend:
  name: github
  branch: main
  repo: lucaoskaique/blog.lucaskaique.com.br
  base_url: https://blog.lucaskaique.com.br/
  auth_endpoint: api/auth/

media_folder: public/assets/img
public_folder: /assets/img
publish_mode: editorial_workflow
slug:
  encoding: "ascii"
  clean_accents: true

collections:
  - name: posts
    label: posts
    folder: posts
    create: true
    slug: "{{slug}}"
    media_folder: "/public/images/{{slug}}"
    public_folder: "/images/{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - {
          label: "Date",
          name: "date",
          widget: "datetime",
          format: "YYYY-MM-DD hh:mm:ss"
        }
      - { label: "Post Image", name: "image", widget: "image", required: false }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - {
          label: "Main Class",
          name: "main-class",
          widget: "select",
          options: ["css", "js", "html", "svg", "dev", "misc", "music"]
        }
      - {
          label: "Color",
          name: "color",
          widget: "select",
          options:
            [
              { label: "CSS", value: "#2DA0C3" },
              { label: "JS", value: "#D6BA32" },
              { label: "HTML", value: "#EB7728" },
              { label: "SVG", value: "#7D669E" },
              { label: "Dev", value: "#637a91" },
              { label: "Misc", value: "#7AAB13" },
              { label: "Music", value: "#6B4C9A" }
            ]
        }
      - { label: "Tags", name: "tags", widget: "list", default: [""] }
      - {
          label: "Category",
          name: "categories",
          widget: "list",
          required: false
        }
      - { label: "Body", name: "body", widget: "markdown" }
